FORMAT: 1A
HOST: http://localhost:9003

# Schema Manager APIs

## Table Schema [/dataTableSchemas/{tableId}]

### Retrieve schema of a datatable [GET]
+ Parameters
    - tableId: 1 (number, required) - The identifier of the Databable

+ Attributes (Table)

## Data Structures

### Table (object)
+ dataTableId: 101 (number, required) - the id of a datatable
+ dataTableName: control test (string) - the name of a datatable
+ fieldDefinitions: (array[Schema]) - list of field definitions

### Schema (object)
+ attributeFormat: pretty (string) - the format of an attribute
+ attributeType: numeric (string) - the attribute type
+ displayName: `The Main Table ID` (string) - the display name of the field
+ fieldName: id (string) - the name of the field
+ position: 1 (number, required) - the position of the field





