FORMAT: 1A
HOST: http://localhost:9003

# Schema Manager APIs

# Group DataTable Schema

THis is a group for Schema related resources

## DataTable Schema [/dataTableSchemas/{tableId}]

### List the schema of one table [GET]

+ Response 200 (application/json)

{
    "dataTableId": 1,
    "dataTableName": "controlTest",
    "fieldDefinitions": [
        {
            "attributeFormat": "pretty",
            "attributeType": "numeric",
            "displayName": "The Main Table ID",
            "fieldName": "id",
            "position": 1
        },
        {
            "attributeFormat": "json",
            "attributeType": "character",
            "displayName": "NaMe",
            "fieldName": "alias",
            "position": 2
        }
    ]
}





