FORMAT: 1A
HOST: http://localhost:9003

# Schema Manager APIs

# Group DataTable Schema

THis is a group for Schema related resources

## DataTable Schema [/dataTableSchemas/{tableId}]

### List the schema of one table [GET]

+ Response 200 (application/json)

hello world!





